### ISSUE TITLE
[BUG 1.16-fabric] Error loading saved data when i start my server

### ISSUE THREAD

**Issue by MaoDoBan** [TheRandomLabs/VanillaDeathChest#34]
I am on:
windows 10
java 1.8.0_231
minecraft 1.16.1
fabricloader@0.8.9+build.203
fabric-api-0.14.1+build.372-1.16
vanilladeathchest-1.16.1-1.11.0.2-fabric

When i start my server, in console this error apears, and "old" death chests dont works properly:
[21:29:55] [Server thread/INFO]: Done (6.734s)! For help, type "help"
[21:29:56] [Server thread/ERROR]: Error loading saved data: vanilladeathchest
java.lang.IllegalArgumentException: Expected UUID-Tag to be of type INT[], but found COMPOUND.
	at net.minecraft.class_2512.method_25930(class_2512.java:168) ~[intermediary-server.jar:?]
	at com.therandomlabs.vanilladeathchest.world.storage.VDCSavedData.method_77(VDCSavedData.java:83) ~[vanilladeathchest-1.16.1-1.11.0.2-fabric.jar:?]
	at net.minecraft.class_26.method_120(class_26.java:72) ~[intermediary-server.jar:?]
	at net.minecraft.class_26.method_20786(class_26.java:58) ~[intermediary-server.jar:?]
	at net.minecraft.class_26.method_17924(class_26.java:42) ~[intermediary-server.jar:?]
	at com.therandomlabs.vanilladeathchest.world.storage.VDCSavedData.get(VDCSavedData.java:124) ~[vanilladeathchest-1.16.1-1.11.0.2-fabric.jar:?]
	at com.therandomlabs.vanilladeathchest.handler.DeathChestContentsChecker.worldTick(DeathChestContentsChecker.java:55) ~[vanilladeathchest-1.16.1-1.11.0.2-fabric.jar:?]
	at com.therandomlabs.vanilladeathchest.handler.DeathChestContentsChecker.tick(DeathChestContentsChecker.java:46) ~[vanilladeathchest-1.16.1-1.11.0.2-fabric.jar:?]
	at net.fabricmc.fabric.api.event.server.ServerTickCallback.lambda$null$0(ServerTickCallback.java:39) ~[37b8c459-2311-4d5b-9b3c-046393b6ba24.jar:?]
	at net.fabricmc.fabric.impl.event.lifecycle.LegacyEventInvokers.lambda$onInitialize$2(LegacyEventInvokers.java:33) ~[37b8c459-2311-4d5b-9b3c-046393b6ba24.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zzp000$onEndTick(MinecraftServer.java:1735) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:855) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:672) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

I tested death, stop the server, start the server, join and see the death chest, which was with my items but did not disappear after I emptied it.

**Comment by TheRandomLabs** [comment]
Thanks for reporting!
