### ISSUE TITLE
Crashes on 1.13.2

### ISSUE THREAD

**Issue by Seegras** [TheRandomLabs/VanillaDeathChest#4]
On 1.13.2, using Rift from: https://minecraft.curseforge.com/linkout?remoteUrl=https://jitpack.io/com/github/chocohead/rift/2c400465c7e0b5abf4e643372fbd9a7e6d39e3ff/rift-2c400465c7e0b5abf4e643372fbd9a7e6d39e3ff.jar

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:28) ~[rift-1.0.4-SNAPSHOT.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:26) ~[rift-1.0.4-SNAPSHOT.jar:?]
	... 2 more
Caused by: java.lang.NoSuchFieldError: a
	at com.therandomlabs.vanilladeathchest.config.VDCConfig$Spawning.<init>(VDCConfig.java:103) ~[vanilladeathchest-1.13-1.5.0.5-rift.jar:?]
	at com.therandomlabs.vanilladeathchest.config.VDCConfig.<clinit>(VDCConfig.java:121) ~[vanilladeathchest-1.13-1.5.0.5-rift.jar:?]
	at com.therandomlabs.vanilladeathchest.VanillaDeathChest.onInitialization(VanillaDeathChest.java:29) ~[vanilladeathchest-1.13-1.5.0.5-rift.jar:?]
	at org.dimdev.riftloader.RiftLoader.initMods(RiftLoader.java:189) ~[rift-1.0.4-SNAPSHOT.jar:?]
	at org.dimdev.riftloader.RiftLoader.load(RiftLoader.java:54) ~[rift-1.0.4-SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:26) ~[rift-1.0.4-SNAPSHOT.jar:?]
	... 2 more

**Comment by TheRandomLabs** [comment]
VanillaDeathChest does not support 1.13.2, but it shouldn't be too difficult to release a version that does.

**Comment by TheRandomLabs** [comment]
I've uploaded a 1.13.2 build to CurseForge.
