### ISSUE TITLE
Crash with [1.16.3] Fabric API 0.25.0 build 415

### ISSUE THREAD

**Issue by L0rdLogan** [TheRandomLabs/VanillaDeathChest#45]
[20:32:07] [main/INFO]: Loading for game Minecraft 1.16.3
[20:32:08] [main/INFO]: [FabricLoader] Loading 105 mods: fabric-keybindings-v0@0.2.0+3fa9f7c595, couplings@1.3.1, cloth-common-events-v1@1.4.8, fabricloader@0.10.1+build.209, adapaxels@1.0.3, cloth-durability-bar-api-v1@1.4.8, fabric-game-rule-api-v1@1.0.3+a4467d2a95, ae2uc@1.1.0-1.16.2, fabric-api-base@0.2.0+9f0fb4b895, reborncore@4.5.0+build.84, xaeroworldmap@1.11.0, fiber@0.23.0-1, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8995, simple_backpack@1.0.29, libblockattributes_items@0.8.2, fabric@0.24.3+build.414-1.16, fabric-networking-v0@0.1.10+e00ecb5f95, techreborn@3.6.1+build.143, cotton-config@1.0.0-rc.7, imm_ptl_core@0.40, fabric-screen-handler-api-v1@1.1.0+8724984195, tk_valoeghese_zoesteriaconfig@1.3.2, com_github_therandomlabs_trlutils-config@master-SNAPSHOT, modmenu@1.14.6+build.31, simpledrawers@1.8.0-1.16.3, cloth-utils-v1@1.4.8, fabric-tool-attribute-api-v1@1.2.4+2b46237995, cloth-client-events-v0@1.4.8, org_apache_commons_commons-compress@1.19, fabric-events-interaction-v0@0.4.1+f8ac1db295, fabric-crash-report-info-v1@0.1.2+b7f9825d95, mostructures@1.0.0-pre3+mc.1.16.2, patchouli@1.16.2-44-FABRIC, fabric-key-binding-api-v1@1.0.1+730711c695, fabric-language-scala@0.3.2.12, cloth-config2@4.8.2, org_tukaani_xz@1.8, fabric-resource-loader-v0@0.3.1+facf3bbf95, chainmail@0.5.0, expandedstorage@5.6.30, cardinal-components-entity@2.6.0, libblockattributes_fluids@0.8.2, fabric-registry-sync-v0@0.6.1+a4467d2a95, cardinal-components-base@2.6.0, fabric-mining-levels-v0@0.1.2+b764ce9995, charm@2.0.3, fabric-models-v0@0.1.1+f8ac1db295, fabric-item-groups-v0@0.2.1+a4467d2a95, fabric-renderer-api-v1@0.3.3+a4467d2a95, linkedstorage@1.3.9-1.16, libcd@3.0.2+1.16.2, cavebiomes@0.4.0, fabric-structure-api-v1@1.1.0+f8ac1db295, nomadbooks@0.5.6, com_github_shevek_parallelgzip@master-SNAPSHOT, lithium@0.5.6, fabric-containers-v0@0.1.8+045df74f95, fabric-object-builder-api-v1@1.9.2+a89534ab95, libblockattributes@0.8.2, appliedenergistics2@8.1.0-alpha.10, fabric-rendering-data-attachment-v1@0.1.4+f8ac1db295, cloth-dynamic-registry-api-v1@1.4.8, fabric-textures-v0@1.0.5+a4467d2a95, com_electronwill_night-config_core@3.6.0, olifantenpad@1.0.0, fabric-rendering-fluids-v1@0.1.12+f8ac1db295, lengthyladders@1.0.1, cloth-scissors-api-v1@1.4.8, trees-do-not-float@1.12.97, environmentalcreepers@1.6.0, cotton-logging@1.0.0-rc.4, fabric-lifecycle-events-v1@1.2.0+74cc3b2095, immersive_portals@0.40, fabric-renderer-registries-v1@2.2.0+f8ac1db295, com_github_therandomlabs_trlutils-fabric@1.16-SNAPSHOT, fabric-loot-tables-v1@1.0.1+432ea18895, cloth-armor-api-v1@1.4.8, fabric-particles-v1@0.2.2+fb0d9b0e95, libblockattributes_core@0.8.2, minecraft@1.16.3, fabric-networking-blockentity-v0@0.2.5+b50ffc7b95, dynmap@3.1-beta4, jankson@3.0.1+j1.2.0, cloth-basic-math@0.5.1, fabric-renderer-indigo@0.4.3+a4467d2a95, com_electronwill_night-config_toml@3.6.0, fluidtank@16.0.6-fabric, fabric-item-api-v1@1.2.0+f8ac1db295, xaerominimap@20.25.0, fabric-rendering-v0@1.1.1+f8ac1db295, fabric-rendering-v1@1.3.1+f8ac1db295, autoconfig1u@3.2.2, fabric-content-registries-v0@0.1.9+059ea86695, fabric-tag-extensions-v0@1.0.3+ac8e8c5995, fabric-biome-api-v1@2.0.0+c29459ab95, vanilladeathchest@1.16.3-1.11.0.7-fabric, cloth-api@1.4.8, textile_backup@2.0.1-1.16.3, byg@1.0.13, carrier@1.3.0, cloth-datagen-api-v1@1.4.8, fabric-events-lifecycle-v0@0.2.0+16acbe5b95, betterend@0.3.1-alpha, team_reborn_energy@0.1.0, fabric-object-builders-v0@0.7.1+a4467d2a95
[20:32:08] [main/WARN]: Mod `com_github_therandomlabs_trlutils-config` (master-SNAPSHOT) does not respect SemVer - comparison support is limited.
[20:32:08] [main/WARN]: Mod `fabric-language-scala` (0.3.2.12) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[20:32:08] [main/WARN]: Mod `com_github_shevek_parallelgzip` (master-SNAPSHOT) does not respect SemVer - comparison support is limited.
[20:32:08] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Administrator/Desktop/1.16.3%20Fabric%20server/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[20:32:13] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-v[20:32:13] [main/WARN]: Force-disabling mixin 'world.player_chunk_t[20:32:13] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in imm_ptl.mixins.json:common.entity_sync.MixinE[20:32:20] [main/FATAL]: Failed to start the minecraft server
net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'vanilladeathchest'
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:193) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:268) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
	at net.minecraft.server.Main.main(Main.java:93) [intermediary-server.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:227) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/command/v1/CommandRegistrationCallback
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_251]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_251]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_251]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_251]
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:186) ~[fabric-server-launch.jar:?]
	... 19 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.command.v1.CommandRegistrationCallback
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:166) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_251]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_251]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_251]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_251]
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:186) ~[fabric-server-launch.jar:?]
	... 19 more

**Comment by TheRandomLabs** [comment]
You'll need to update Fabric Loader. 😄

**Comment by L0rdLogan** [comment]
> You'll need to update Fabric Loader. 😄

Thank you. This was a server crash so I'll have a look at how I do that
