### ISSUE TITLE
Death Chest didnt spawn

### ISSUE THREAD

**Issue by toinopt** [TheRandomLabs/VanillaDeathChest#51]
I was in a hunting dimension mod named mining dimensions when my pc lagged and i got insta killed by a pigman, since it was a bit late i just changed to creative to get there faster and go to sleep, when i got to the spot there was no chest, it happened in version 2.0.4
Saw a issue that after the new update to 2.0.5 it started working again and i tried it in the hope it would spawn the chest but it didnt :(
It was working previously but i havent died in the last 2 or 3 days so it might have stopped working in that time 

Here is the deathchest.dat from the hunting dimension where i died
[deathchests.zip](https://github.com/TheRandomLabs/VanillaDeathChest/files/5992184/deathchests.zip)

This is the log part after i died related to the chest not spawning
[22:17:24] [Server thread/INFO]: Omarelio was slain by Piglin Brute
[22:17:24] [Server thread/WARN]: Fetching packet for removed entity class_1542['Gamer Axe'/56012, l='ServerLevel[Toino]', x=-167.83, y=65.32, z=232.84]
[22:17:24] [Server thread/WARN]: Fetching packet for removed entity class_1542['Modular Mining Drill'/56013, l='ServerLevel[Toino]', x=-167.83, y=65.32, z=232.84]
[22:17:24] [Server thread/WARN]: Fetching packet for removed entity class_1542['Dank 4'/56014, l='ServerLevel[Toino]', x=-167.83, y=65.32, z=232.84]
[22:17:24] [Server thread/WARN]: Fetching packet for removed entity class_1542['Waystone'/56015, l='ServerLevel[Toino]', x=-167.83, y=65.32, z=232.84]
[22:17:24] [Server thread/WARN]: Fetching packet for removed entity class_1542['Torch'/56016, l='ServerLevel[Toino]', x=-167.83, y=65.32, z=232.84]
[22:17:24] [Server thread/WARN]: Fetching packet for removed entity class_1542['Biome Locator'/56017, l='ServerLevel[Toino]', x=-167.83, y=65.32, z=232.84]
[22:17:24] [Server thread/WARN]: Fetching packet for removed entity class_1542['Time in a Bottle'/56018, l='ServerLevel[Toino]', x=-167.83, y=65.32, z=232.84]
[22:17:24] [Server thread/WARN]: Fetching packet for removed entity class_1542['Pocket Crafting Table'/56019, l='ServerLevel[Toino]', x=-167.83, y=65.32, z=232.84]
[22:17:24] [Server thread/WARN]: Fetching packet for removed entity class_1542['Cooked Cod'/56020, l='ServerLevel[Toino]', x=-167.83, y=65.32, z=232.84]
[22:17:24] [Server thread/WARN]: Fetching packet for removed entity class_1542['Sapphire Boots'/56021, l='ServerLevel[Toino]', x=-167.83, y=65.32, z=232.84]
[22:17:24] [Server thread/WARN]: Fetching packet for removed entity class_1542['Golden Leggings'/56022, l='ServerLevel[Toino]', x=-167.83, y=65.32, z=232.84]
[22:17:24] [Server thread/WARN]: Fetching packet for removed entity class_1542['Sapphire Chestplate'/56023, l='ServerLevel[Toino]', x=-167.83, y=65.32, z=232.84]
[22:17:24] [Server thread/WARN]: Fetching packet for removed entity class_1542['Sapphire Helmet'/56024, l='ServerLevel[Toino]', x=-167.83, y=65.32, z=232.84]
[22:17:24] [Server thread/WARN]: Fetching packet for removed entity class_1542['Dome of the Strider'/56025, l='ServerLevel[Toino]', x=-167.83, y=65.32, z=232.84]
[22:17:24] [Server thread/WARN]: Fetching packet for removed entity class_1542['Superstitious Hat'/56026, l='ServerLevel[Toino]', x=-167.83, y=65.32, z=232.84]
[22:17:24] [Server thread/WARN]: Fetching packet for removed entity class_1542['Blazing Backpack'/56027, l='ServerLevel[Toino]', x=-167.83, y=65.32, z=232.84]
[22:17:24] [Server thread/WARN]: Fetching packet for removed entity class_1542['Cross Necklace'/56028, l='ServerLevel[Toino]', x=-167.83, y=65.32, z=232.84]
[22:17:24] [Server thread/WARN]: Fetching packet for removed entity class_1542['Cloud in a Bottle'/56029, l='ServerLevel[Toino]', x=-167.83, y=65.32, z=232.84]
[22:17:24] [Server thread/WARN]: Fetching packet for removed entity class_1542['Flippers'/56030, l='ServerLevel[Toino]', x=-167.83, y=65.32, z=232.84]
[22:17:24] [Server thread/WARN]: Fetching packet for removed entity class_1542['Power Glove'/56031, l='ServerLevel[Toino]', x=-167.83, y=65.32, z=232.84]
[22:17:24] [Server thread/WARN]: Fetching packet for removed entity class_1542['Digging Claws'/56032, l='ServerLevel[Toino]', x=-167.83, y=65.32, z=232.84]
[22:17:24] [main/INFO]: [CHAT] Omarelio was slain by Piglin Brute
[22:17:24] [Server thread/INFO]: Death chest for Omarelio spawned at [-168, 64, 232] with identifier 0a935aa9-0d42-455d-924d-aad2f6e4a8a7
[22:17:24] [main/INFO]: [CHAT] Death chest spawned at [-168, 64, 232]
[22:17:30] [main/INFO]: Loading slotlock file
[22:17:30] [main/INFO]: Successfully loaded slotlock file
[22:17:30] [main/INFO]: Stopping worker threads
[22:17:30] [main/INFO]: Started 4 worker threads
[22:17:30] [main/INFO]: Stopping worker threads
[22:17:30] [main/INFO]: Started 4 worker threads
[22:17:30] [CraftPresence/ERROR]: Asset name "overworld" does not exist, attempting to use an alternative icon "aof_-_tile_cover_test_02"...
[22:17:30] [CraftPresence/INFO]: To add support for this icon, please request for this icon to be added to the default Client ID or add the icon under the following name: "overworld".
[22:17:30] [CraftPresence/INFO]: Fallback icon for "overworld" found! Using a fallback icon with the name "aof_-_tile_cover_test_02"!
[22:17:56] [main/INFO]: [CHAT] Unknown or incomplete command, see below for error
[22:17:56] [main/INFO]: [CHAT] /gamemode<--[HERE]
[22:18:03] [Server thread/INFO]: [Omarelio: Set own game mode to Creative Mode]
[22:18:03] [main/INFO]: [CHAT] Set own game mode to Creative Mode
[22:18:10] [main/INFO]: Loading slotlock file
[22:18:10] [main/INFO]: Successfully loaded slotlock file
[22:18:10] [main/INFO]: Stopping worker threads
[22:18:10] [main/INFO]: Started 4 worker threads
[22:18:10] [main/INFO]: Stopping worker threads
[22:18:10] [main/INFO]: Started 4 worker threads
[22:18:10] [CraftPresence/ERROR]: Asset name "hunting_dim" does not exist, attempting to use an alternative icon "aof_-_tile_cover_test_02"...
[22:18:10] [CraftPresence/INFO]: To add support for this icon, please request for this icon to be added to the default Client ID or add the icon under the following name: "hunting_dim".
[22:18:10] [CraftPresence/INFO]: Fallback icon for "hunting_dim" found! Using a fallback icon with the name "aof_-_tile_cover_test_02"!
[22:19:03] [Server thread/ERROR]: Failed to load data for block entity minecraft:chest
java.lang.NullPointerException: null
	at com.therandomlabs.vanilladeathchest.world.DeathChestsState.get(DeathChestsState.java:198) ~[vanilladeathchest-2.0.4-fabric.jar:?]
	at net.minecraft.class_2624.handler$zph000$fromTag(class_2624.java:567) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_2624.method_11014(class_2624.java:37) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_2595.method_11014(class_2595.java:60) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_2586.method_17897(class_2586.java:86) ~[intermediary-1.16.5.jar:?]
	at java.util.Optional.map(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.class_2586.method_11005(class_2586.java:84) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_2852.method_12386(class_2852.java:394) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_2852.method_12388(class_2852.java:138) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_2818.method_12206(class_2818.java:479) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_3898.method_17227(class_3898.java:622) ~[intermediary-1.16.5.jar:?]
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.class_3898.method_20460(class_3898.java:611) ~[intermediary-1.16.5.jar:?]
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.class_3900.method_17634(class_3900.java:58) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:545) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:554) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_3215.getChunkBlocking(class_3215.java:1269) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_3215.method_12121(class_3215.java:1165) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1937.getChunkLithium(class_1937.java:6240) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1937.method_22350(class_1937.java:6216) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1937.method_8500(class_1937.java:6211) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1937.method_8321(class_1937.java:610) ~[intermediary-1.16.5.jar:?]
	at com.therandomlabs.vanilladeathchest.deathchest.DeathChestAutoRemover.removeIfEmpty(DeathChestAutoRemover.java:68) ~[vanilladeathchest-2.0.4-fabric.jar:?]
	at com.therandomlabs.vanilladeathchest.deathchest.DeathChestAutoRemover.removeEmpty(DeathChestAutoRemover.java:54) ~[vanilladeathchest-2.0.4-fabric.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:108) ~[6c1a6f2c-3ac3-4137-93cb-8b65207f5ad2.jar:?]
	at net.minecraft.class_1937.handler$dii000$tickWorldAfterBlockEntities(class_1937.java:8275) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1937.method_18471(class_1937.java:557) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:429) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:91) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-1.16.5.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
[22:19:03] [Server thread/WARN]: Skipping BlockEntity with id minecraft:chest
[22:19:47] [Server thread/INFO]: Omarelio has made the advancement [A Bigger Throwaway Joke]
[22:19:47] [main/INFO]: [CHAT] Omarelio has made the advancement [A Bigger Throwaway Joke]
[22:19:47] [main/INFO]: Loaded 880 advancements
[22:20:27] [Server thread/INFO]: Villager class_1646['Villager'/58712, l='ServerLevel[Toino]', x=-146.01, y=63.00, z=240.98] died, message: 'Villager was slain by Zombie'
[22:20:27] [main/INFO]: Villager class_1646['Villager'/58712, l='ClientLevel', x=-146.10, y=63.39, z=240.69] died, message: 'Villager died'
[22:20:27] [main/INFO]: Loaded 882 advancements
[22:20:31] [Server thread/INFO]: Saving and pausing game...
[22:20:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/minecraft:overworld
[22:20:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/minecraft:the_nether
[22:20:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/minecraft:the_end
[22:20:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/mining_dims:caving_dim
[22:20:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/mining_dims:hunting_dim
[22:20:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/mining_dims:mining_dim
[22:20:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/appliedenergistics2:spatial_storage
[22:20:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/mining_dims:nethering_dim
[22:20:32] [main/ERROR]: Invalid mod icon for icon source advdebug: assets/modid/icon.png
java.nio.file.NoSuchFileException: assets/modid/icon.png
	at com.sun.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:544) ~[zipfs.jar:1.8.0_281]
	at com.sun.nio.zipfs.ZipPath.newInputStream(ZipPath.java:645) ~[zipfs.jar:1.8.0_281]
	at com.sun.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:278) ~[zipfs.jar:1.8.0_281]
	at java.nio.file.Files.newInputStream(Unknown Source) ~[?:1.8.0_281]
	at com.terraformersmc.modmenu.util.mod.ModIconHandler.createIcon(ModIconHandler.java:33) ~[modmenu-1.16.7.jar:?]
	at com.terraformersmc.modmenu.util.mod.fabric.FabricMod.getIcon(FabricMod.java:166) ~[modmenu-1.16.7.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.bindIconTexture(ModListEntry.java:95) ~[modmenu-1.16.7.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.method_25343(ModListEntry.java:51) ~[modmenu-1.16.7.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModListWidget.method_25311(ModListWidget.java:225) ~[modmenu-1.16.7.jar:?]
	at net.minecraft.class_350.method_25394(class_350.java:206) ~[intermediary-1.16.5.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25394(ModsScreen.java:274) ~[modmenu-1.16.7.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:616) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1048) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) ~[1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) ~[fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) ~[fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) ~[fabric-loader-0.11.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171) ~[?:?]
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53) ~[?:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131) ~[?:?]
	at java.util.HashMap$Values.forEach(Unknown Source) [?:1.8.0_281]
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
[22:20:32] [main/WARN]: Warning! Mod advdebug has a broken icon, loading default icon
[22:20:34] [main/ERROR]: Invalid mod icon for icon source advdebug: assets/modid/icon.png
java.nio.file.NoSuchFileException: assets/modid/icon.png
	at com.sun.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:544) ~[zipfs.jar:1.8.0_281]
	at com.sun.nio.zipfs.ZipPath.newInputStream(ZipPath.java:645) ~[zipfs.jar:1.8.0_281]
	at com.sun.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:278) ~[zipfs.jar:1.8.0_281]
	at java.nio.file.Files.newInputStream(Unknown Source) ~[?:1.8.0_281]
	at com.terraformersmc.modmenu.util.mod.ModIconHandler.createIcon(ModIconHandler.java:33) ~[modmenu-1.16.7.jar:?]
	at com.terraformersmc.modmenu.util.mod.fabric.FabricMod.getIcon(FabricMod.java:166) ~[modmenu-1.16.7.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.bindIconTexture(ModListEntry.java:95) ~[modmenu-1.16.7.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.method_25343(ModListEntry.java:51) ~[modmenu-1.16.7.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModListWidget.method_25311(ModListWidget.java:225) ~[modmenu-1.16.7.jar:?]
	at net.minecraft.class_350.method_25394(class_350.java:206) ~[intermediary-1.16.5.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25394(ModsScreen.java:274) ~[modmenu-1.16.7.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:616) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1048) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) ~[1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) ~[fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) ~[fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) ~[fabric-loader-0.11.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171) ~[?:?]
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53) ~[?:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131) ~[?:?]
	at java.util.HashMap$Values.forEach(Unknown Source) [?:1.8.0_281]
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
[22:20:34] [main/WARN]: Warning! Mod advdebug has a broken icon, loading default icon
[22:20:34] [main/WARN]: Warning! Mod croptosis has a broken icon, loading default icon
[22:20:34] [main/WARN]: Warning! Mod croptosis has a broken icon, loading default icon
[22:20:34] [main/WARN]: Warning! Mod croptosis has a broken icon, loading default icon
[22:20:41] [Server thread/INFO]: Saving and pausing game...
[22:20:41] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/minecraft:overworld
[22:20:41] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/minecraft:the_nether
[22:20:41] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/minecraft:the_end
[22:20:41] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/mining_dims:caving_dim
[22:20:41] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/mining_dims:hunting_dim
[22:20:41] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/mining_dims:mining_dim
[22:20:41] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/appliedenergistics2:spatial_storage
[22:20:41] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/mining_dims:nethering_dim
[22:20:50] [main/INFO]: [CHAT] Mijotisi has been discovered!
[22:21:02] [main/INFO]: [CHAT] Incorrect argument for command
[22:21:02] [main/INFO]: [CHAT] /gamemode s<--[HERE]
[22:21:08] [Server thread/INFO]: Villager class_1646['Beekeeper'/58637, l='ServerLevel[Toino]', x=-216.43, y=63.00, z=282.91] died, message: 'Beekeeper was shot by Pillager'
[22:21:08] [main/INFO]: Villager class_1646['Beekeeper'/58637, l='ClientLevel', x=-217.12, y=63.00, z=283.55] died, message: 'Beekeeper died'
[22:21:09] [Server thread/INFO]: [Omarelio: Set own game mode to Survival Mode]
[22:21:09] [main/INFO]: [CHAT] Set own game mode to Survival Mode
[22:21:15] [Server thread/INFO]: Saving and pausing game...
[22:21:15] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/minecraft:overworld
[22:21:15] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/minecraft:the_nether
[22:21:15] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/minecraft:the_end
[22:21:15] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/mining_dims:caving_dim
[22:21:15] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/mining_dims:hunting_dim
[22:21:15] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/mining_dims:mining_dim
[22:21:15] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/appliedenergistics2:spatial_storage
[22:21:15] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/mining_dims:nethering_dim
[22:26:39] [Server thread/INFO]: Omarelio was slain by Zombie
[22:26:39] [Server thread/WARN]: Fetching packet for removed entity class_1542['Crimson Stem'/59643, l='ServerLevel[Toino]', x=-171.86, y=64.26, z=230.15]
[22:26:39] [main/INFO]: [CHAT] Omarelio was slain by Zombie
[22:26:39] [Server thread/INFO]: Death chest for Omarelio spawned at [-172, 63, 230] with identifier ae1a6d04-bd51-443e-94ca-33720da54c81
[22:26:39] [main/INFO]: [CHAT] Death chest spawned at [-172, 63, 230]
[22:26:40] [main/INFO]: Loading slotlock file
[22:26:40] [main/INFO]: Successfully loaded slotlock file
[22:26:40] [main/INFO]: Stopping worker threads
[22:26:40] [main/INFO]: Started 4 worker threads
[22:26:40] [Server thread/INFO]: Saving and pausing game...
[22:26:40] [main/INFO]: Stopping worker threads
[22:26:40] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/minecraft:overworld
[22:26:40] [main/INFO]: Started 4 worker threads
[22:26:40] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/minecraft:the_nether
[22:26:40] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/minecraft:the_end
[22:26:40] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/mining_dims:caving_dim
[22:26:40] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/mining_dims:hunting_dim
[22:26:40] [CraftPresence/ERROR]: Asset name "overworld" does not exist, attempting to use an alternative icon "aof_-_tile_cover_test_02"...
[22:26:40] [CraftPresence/INFO]: To add support for this icon, please request for this icon to be added to the default Client ID or add the icon under the following name: "overworld".
[22:26:40] [CraftPresence/INFO]: Fallback icon for "overworld" found! Using a fallback icon with the name "aof_-_tile_cover_test_02"!
[22:26:40] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/mining_dims:mining_dim
[22:26:40] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/appliedenergistics2:spatial_storage
[22:26:40] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Toino]'/mining_dims:nethering_dim
[22:27:02] [main/INFO]: [CHAT] Unknown or incomplete command, see below for error
[22:27:02] [main/INFO]: [CHAT] /ob_inventory r.0.0<--[HERE]
[22:28:42] [main/INFO]: [CHAT] Unknown or incomplete command, see below for error
[22:28:42] [main/INFO]: [CHAT] /ob_inventory restore Omarelio<--[HERE]
[22:30:26] [main/INFO]: Loading slotlock file
[22:30:26] [main/INFO]: Successfully loaded slotlock file
[22:30:26] [main/INFO]: Stopping worker threads
[22:30:26] [main/INFO]: Started 4 worker threads
[22:30:26] [main/INFO]: Stopping worker threads
[22:30:26] [main/INFO]: Started 4 worker threads
[22:30:26] [CraftPresence/ERROR]: Asset name "hunting_dim" does not exist, attempting to use an alternative icon "aof_-_tile_cover_test_02"...
[22:30:26] [CraftPresence/INFO]: To add support for this icon, please request for this icon to be added to the default Client ID or add the icon under the following name: "hunting_dim".
[22:30:26] [CraftPresence/INFO]: Fallback icon for "hunting_dim" found! Using a fallback icon with the name "aof_-_tile_cover_test_02"!
[22:30:35] [Server thread/INFO]: [Omarelio: Set own game mode to Creative Mode]
[22:30:35] [main/INFO]: [CHAT] Set own game mode to Creative Mode
[22:31:28] [Server thread/ERROR]: Failed to load data for block entity minecraft:chest
java.lang.NullPointerException: null
	at com.therandomlabs.vanilladeathchest.world.DeathChestsState.get(DeathChestsState.java:198) ~[vanilladeathchest-2.0.4-fabric.jar:?]
	at net.minecraft.class_2624.handler$zph000$fromTag(class_2624.java:567) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_2624.method_11014(class_2624.java:37) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_2595.method_11014(class_2595.java:60) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_2586.method_17897(class_2586.java:86) ~[intermediary-1.16.5.jar:?]
	at java.util.Optional.map(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.class_2586.method_11005(class_2586.java:84) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_2852.method_12386(class_2852.java:394) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_2852.method_12388(class_2852.java:138) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_2818.method_12206(class_2818.java:479) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_3898.method_17227(class_3898.java:622) ~[intermediary-1.16.5.jar:?]
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.class_3898.method_20460(class_3898.java:611) ~[intermediary-1.16.5.jar:?]
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.class_3900.method_17634(class_3900.java:58) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:545) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:554) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_3215.method_19492(class_3215.java:280) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:749) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-1.16.5.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
[22:31:28] [Server thread/WARN]: Skipping BlockEntity with id minecraft:chest

**Comment by TheRandomLabs** [comment]
Can you try `/vdc place 0a935aa9-0d42-455d-924d-aad2f6e4a8a7`?

**Comment by toinopt** [comment]
I was looking for this command, i was already in bed when i found it.
The command worked, might had the same problem the other guy had, since i updated it if anything happens i will report back again, the code saved me from rage quitting :)

**Comment by TheRandomLabs** [comment]
Thank you for putting up with the buggy 2.0.0 versions! 😛
