### ISSUE TITLE
Death Chests Crash Server if Dying in Nether

### ISSUE THREAD

**Issue by ravynhardcastle** [TheRandomLabs/VanillaDeathChest#53]
Title pretty much explains it. If you die in the nether, the server crashes in the newest 2.0.5 alpha build. I tried blacklisting the nether in the config, but it was not at all clear how to do that (I tried "NETHER", "minecraft:the_nether", and -1).  The error is as follows:

`Java.lang.NullPointerException: Ticking entity
	at java.util.Objects.requireNonNull(Objects.java:203)
	at com.therandomlabs.vanilladeathchest.VDCConfig$Spawning.isDimensionEnabled(VDCConfig.java:181)
	at net.minecraft.class_1309.handler$zgl000$dropTail(class_1309.java:26400)
	at net.minecraft.class_1309.method_16080(class_1309.java:1298)
	at net.minecraft.class_3222.method_6078(class_3222.java:540)
	at net.minecraft.class_1309.method_5643(class_1309.java:1106)
	at net.minecraft.class_1657.method_5643(class_1657.java:914)
	at net.minecraft.class_3222.method_5643(class_3222.java:631)
	at net.minecraft.class_1308.method_6121(class_1308.java:1474)
	at net.minecraft.class_1366.method_6288(class_1366.java:142)
	at net.minecraft.class_1366.method_6268(class_1366.java:134)
	at net.minecraft.class_4135.method_6268(class_4135.java:55)
	at net.minecraft.class_1355.tickGoals(class_1355.java:649)
	at net.minecraft.class_1355.method_6275(class_1355.java:556)
	at net.minecraft.class_1308.method_6023(class_1308.java:736)
	at net.minecraft.class_1309.method_6007(class_1309.java:2508)
	at net.minecraft.class_1308.method_6007(class_1308.java:542)
	at net.minecraft.class_1588.method_6007(class_1588.java:43)
	at net.minecraft.class_1560.method_6007(class_1560.java:250)
	at net.minecraft.class_1309.method_5773(class_1309.java:2254)
	at net.minecraft.class_1308.method_5773(class_1308.java:342)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by TheRandomLabs** [comment]
I'll fix the `NullPointerException`, but I don't know the underlying cause. Does this occur when no other mods are installed?

**Comment by TaintedHorizon** [comment]
With All the Fabric 3 2.6.9 (VDC 2.0.5) also have nether crash no death chest spawn/crash server. Just thought I would throw my log in in case it helps. In overworld death chest seems to work ok. I also removed the deathchests.dat and let it re create in an attempt to troubleshoot. Thanks!

[06:46:06] [Server thread/INFO]: "" was slain by Magma Cube
[06:46:06] [Server thread/WARN]: Failed to handle packet for /192.168.2.227:64355
net.minecraft.class_148: Ticking player
	at net.minecraft.class_3222.method_14226(class_3222.java:498) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:219) ~[intermediary-server.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:232) ~[intermediary-server.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:173) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212-1-ojdkbuild]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_212-1-ojdkbuild]
	at com.therandomlabs.vanilladeathchest.VDCConfig$Spawning.isDimensionEnabled(VDCConfig.java:181) ~[vanilladeathchest-2.0.5-fabric.jar:?]
	at net.minecraft.class_1309.handler$bff000$dropTail(class_1309.java:21900) ~[intermediary-server.jar:?]
	at net.minecraft.class_1309.method_16080(class_1309.java:1298) ~[intermediary-server.jar:?]
	at net.minecraft.class_3222.method_6078(class_3222.java:540) ~[intermediary-server.jar:?]
	at net.minecraft.class_1309.method_5643(class_1309.java:1106) ~[intermediary-server.jar:?]
	at net.minecraft.class_1657.method_5643(class_1657.java:914) ~[intermediary-server.jar:?]
	at net.minecraft.class_3222.method_5643(class_3222.java:631) ~[intermediary-server.jar:?]
	at net.minecraft.class_1621.method_7155(class_1621.java:249) ~[intermediary-server.jar:?]
	at net.minecraft.class_1621.method_5694(class_1621.java:241) ~[intermediary-server.jar:?]
	at net.minecraft.class_1657.method_7341(class_1657.java:621) ~[intermediary-server.jar:?]
	at net.minecraft.class_1657.method_6007(class_1657.java:597) ~[intermediary-server.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2254) ~[intermediary-server.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:274) ~[intermediary-server.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:434) ~[intermediary-server.jar:?]
