### ISSUE TITLE
Death Chest didn't spawn, Server Crashed.

### ISSUE THREAD

**Issue by HundredMinusOne** [TheRandomLabs/VanillaDeathChest#63]
Okay so I'm pretty sure this was my fault, but I died in lava BUT right as I was dying, I instinctively logged out to try and avoid the last tick of fire damage (normally play vanilla survival so the death chest thing didn't cross my mind). Doing so resulted in this

________________________________________________________________________________________________________________________________________

[22:15:24] [Server thread/INFO]: HundredMinus1 tried to swim in lava
[22:15:24] [Server thread/ERROR]: Failed to determine dimension
java.lang.RuntimeException: null
	at com.therandomlabs.vanilladeathchest.VDCConfig$Spawning.isDimensionEnabled(VDCConfig.java:183) ~[vanilladeathchest-2.0.6-fabric.jar:?]
	at net.minecraft.class_1309.handler$zhi000$dropTail(class_1309.java:32400) ~[intermediary-server.jar:?]
	at net.minecraft.class_1309.method_16080(class_1309.java:1298) ~[intermediary-server.jar:?]
	at net.minecraft.class_3222.method_6078(class_3222.java:540) ~[intermediary-server.jar:?]
	at net.minecraft.class_1309.method_5643(class_1309.java:1106) ~[intermediary-server.jar:?]
	at net.minecraft.class_1657.method_5643(class_1657.java:914) ~[intermediary-server.jar:?]
	at net.minecraft.class_3222.method_5643(class_3222.java:631) ~[intermediary-server.jar:?]
	at net.minecraft.class_1297.method_5730(class_1297.java:520) ~[intermediary-server.jar:?]
	at net.minecraft.class_1297.method_5670(class_1297.java:479) ~[intermediary-server.jar:?]
	at net.minecraft.class_1309.method_5670(class_1309.java:324) ~[intermediary-server.jar:?]
	at net.minecraft.class_1297.method_5773(class_1297.java:431) ~[intermediary-server.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2209) ~[intermediary-server.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:274) ~[intermediary-server.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:434) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:219) ~[intermediary-server.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:232) ~[intermediary-server.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:173) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
[22:15:24] [Server thread/INFO]: Death chest for HundredMinus1 queued at [3636, 30, 4842] with identifier bfd66404-b47e-44d5-a51a-32d1c70c2e39
[22:15:24] [Server thread/INFO]: HundredMinus1 lost connection: Disconnected
[22:15:24] [Server thread/INFO]: HundredMinus1 left the game
[22:15:24] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception ticking world
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
Caused by: java.lang.NullPointerException
	at net.minecraft.class_1838.<init>(class_1838.java:24) ~[intermediary-server.jar:?]
	at com.therandomlabs.vanilladeathchest.deathchest.DeathChestLocationFinder.canPlace(DeathChestLocationFinder.java:198) ~[vanilladeathchest-2.0.6-fabric.jar:?]
	at com.therandomlabs.vanilladeathchest.deathchest.DeathChestLocationFinder.find(DeathChestLocationFinder.java:152) ~[vanilladeathchest-2.0.6-fabric.jar:?]
	at com.therandomlabs.vanilladeathchest.deathchest.DeathChestPlacer.place(DeathChestPlacer.java:306) ~[vanilladeathchest-2.0.6-fabric.jar:?]
	at com.therandomlabs.vanilladeathchest.deathchest.DeathChestPlacer.placeAndDropRemaining(DeathChestPlacer.java:242) ~[vanilladeathchest-2.0.6-fabric.jar:?]
	at com.therandomlabs.vanilladeathchest.deathchest.DeathChestPlacer.placeQueued(DeathChestPlacer.java:96) ~[vanilladeathchest-2.0.6-fabric.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$4(ServerTickEvents.java:84) ~[c473da63-fd97-4588-b13c-7844399fcf0b.jar:?]
	at net.minecraft.class_3218.handler$cle000$startWorldTick(class_3218.java:10587) ~[intermediary-server.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:235) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871) ~[intermediary-server.jar:?]
	... 5 more
[22:15:24] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Blind\OneDrive - Georgia Military College\Desktop\AllofFabric3Server-2.7.2\.\crash-reports\crash-2021-05-26_22.15.24-server.txt
[22:15:24] [Server thread/INFO]: Stopping server
[22:15:24] [Server thread/INFO]: Saving players
[22:15:24] [Server thread/INFO]: Saving worlds
[22:15:24] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[22:15:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[22:15:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[22:15:26] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[22:15:26] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[22:15:26] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[22:15:26] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[22:15:26] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[22:15:26] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[22:15:26] [Server thread/WARN]: tilesToReady should be empty at server shutdown.

________________________________________________________________________________________________________________________________________

If you would like the entire log, just let me know. 
Thank you!

**Comment by HundredMinusOne** [comment]
Oh yea, I forgot to say that I used the command "/vdc place bfd66404-b47e-44d5-a51a-32d1c70c2e39" and it says "Invalid Death Chest Identifier". So that sucks, any thoughts?
